[package]
name = "camera-intrinsic-calibration"
version = "0.4.2"
edition = "2021"
authors = ["Powei Lin <poweilin1994@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"
description = "Camera Intrinsic Calibration"
homepage = "https://github.com/powei-lin/camera-intrinsic"
repository = "https://github.com/powei-lin/camera-intrinsic"
keywords = ["camera-intrinsic", "intrinsic", "fisheye"]
categories = ["data-structures", "science", "mathematics", "science::robotics"]
exclude = ["/.github/*", "*.ipynb", "./scripts/*", "examples/*", "tests/*", "./data/*"]

[dependencies]
aprilgrid = "0.4.1"
camera-intrinsic-model = "0.3.1"
clap = { version = "4.5.23", features = ["derive"] }
colorous = "1.0.15"
env_logger = "0.11.5"
faer = "0.19.4"
glam = "0.29.2"
glob = "0.3.1"
image = "0.25.5"
indicatif = { version = "0.17.9", features = ["rayon"] }
log = "0.4.22"
nalgebra = "0.33.2"
num-dual = "0.10.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.10.0"
rerun = "0.17.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sqpnp_simple = "0.1.5"
time = "0.3.37"
tiny-solver = "0.11.0"

[[bin]]
name = "ccrs"
path = "src/bin/camera_calibration.rs"
test = false
bench = false

[[example]]
name = "convert_model"
path = "examples/convert_model.rs"

[[example]]
name = "test_pnp"
